theme: jekyll-theme-minimal
title: CPG Bioinformatics Nepal Training Feb 2026
description: Hands-on training for analysing Oxford Nanopore Technologies (ONT) sequencing data for microbial pathogen detection
