theme: jekyll-theme-minimal
logo: /logo.png
title: CPG Bioinformatics Nepal Training Feb 2026
google_analytics:
description: Hands-on training for analysing Oxford Nanopore Technologies (ONT) sequencing data for microbial pathogen detection
